### ISSUE TITLE
Ask for the release timeline of online model converter

### ISSUE THREAD

**Issue by evitself** [HornedSungem/SungemSDK#13]
Hi, Dear HS Team,
I have tried your product, it is awesome! Just one thing that I would like to know, would you please share an estimated timeline for the online model conversion tool to be available? I would like to try out some of my own caffe/tf models.

Thanks!

**Comment by HornedSungem** [comment]
Hi, you can try the tools:
https://github.com/HornedSungem/SungemSDK-Python/tree/master/tool
