### ISSUE TITLE
Cound not open HS device

### ISSUE THREAD

**Issue by firecloudy** [HornedSungem/SungemSDK#14]
pi@raspberrypi:~/AI_Dev/SungemSDK/examples/python $ python3 Hello2018.py 
| ======= Horned Sungem ======== |
Traceback (most recent call last):
  File "Hello2018.py", line 10, in <module>
    net = hs.HS('mnist')
  File "../../api/hsapi.py", line 357, in __init__
    self.device.OpenDevice()
  File "../../api/hsapi.py", line 147, in OpenDevice
    raise Exception(Status(status))
Exception: hsStatus.ERROR

python3 ObjectDetector.py 
| ======= Horned Sungem ======== |
Traceback (most recent call last):
  File "ObjectDetector.py", line 11, in <module>
    net = hs.HS('ObjectDetector', zoom = True, verbose = 2)
  File "../../api/hsapi.py", line 357, in __init__
    self.device.OpenDevice()
  File "../../api/hsapi.py", line 147, in OpenDevice
    raise Exception(Status(status))
Exception: hsStatus.ERROR

python3 upgrade.py -f ../../senscape_release_usbdown_v1.0.0_20180622.bin
Firmware Upgrade
Error - Cound not open HS device.

pi@raspberrypi:~/AI_Dev/SungemSDK/api $ lsusb
Bus 001 Device 007: ID 045e:0084 Microsoft Corp. Basic Optical Mouse
Bus 001 Device 005: ID 413c:2003 Dell Computer Corp. Keyboard
Bus 001 Device 004: ID 0bda:5411 Realtek Semiconductor Corp. 
Bus 001 Device 011: ID 03e7:f63b
Bus 001 Device 006: ID 0424:7800 Standard Microsystems Corp. 
Bus 001 Device 003: ID 0424:2514 Standard Microsystems Corp. USB 2.0 Hub
Bus 001 Device 002: ID 0424:2514 Standard Microsystems Corp. USB 2.0 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**Comment by ldseraph** [comment]
你先试一下 在前面添加 sudo

**Comment by Mebigger** [comment]
@jinke5245 
请问在哪里复制你所说的文件`99-hornedsungem.rules`
