### ISSUE TITLE
loadtensor里的tensor参数在C语言里是什么类型的数据啊？

### ISSUE THREAD

**Issue by laimingzhe** [HornedSungem/SungemSDK#15]
python用了tostring ，c语言里要怎么写啊？

**Comment by laimingzhe** [comment]
hsLoadTensor 就是这个函数的inputTensor  我应该传什么数据进去？我在c++里直接传图像的数据，说是无效的数据。

**Comment by HornedSungem** [comment]
C++版本的示例大概本周给出，可以参照示例。
