### ISSUE TITLE
打开设备报错

### ISSUE THREAD

**Issue by thunder95** [HornedSungem/SungemSDK#18]
运行示例程序Hello2018发生报错：
![qq 20181226142059](https://user-images.githubusercontent.com/22673612/50434736-7dbecf00-0919-11e9-952b-ecc76e565136.png)

设备在ubuntu里能检测到，并被SDB识别，但是就是打不开，指示灯只有一个红色和绿色的，未见蓝色的灯闪亮。
![qq 20181226142223](https://user-images.githubusercontent.com/22673612/50434781-b2cb2180-0919-11e9-97b1-d4a3535b6eff.png)

**Comment by HornedSungem** [comment]
有三种可能：1：固件版本低了，烧写最新版本固件。2：没有USB读写权限，检查 /etc/udev/rules.d 目录下 99-hornedsungem.rules 文件是否存在。3：虚拟机USB配置问题，将USB兼容性设置为 USB 3.0，检查是否安装 VMWare Tools。

**Comment by HornedSungem** [comment]
在QQ群里也回答您了。

**Comment by HornedSungem** [comment]
您也可以查看我们的FAQ：
https://hornedsungem.senscape.cn/Docs/faq/

**Comment by thunder95** [comment]
按你给的提示已经调好了
