### ISSUE TITLE
使用USB摄像头和内置摄像头有效率的差别吗？

### ISSUE THREAD

**Issue by gallex** [HornedSungem/SungemSDK#19]

**Comment by HornedSungem** [comment]
<img width="959" alt="image" src="https://user-images.githubusercontent.com/36222683/50570052-99145900-0db5-11e9-9553-496bba9b7e68.png">

**Comment by HornedSungem** [comment]
效率上来说差别不大，主要是图像质量区别。外置USB摄像头可以自选合适的摄像头，更灵活。
