### ISSUE TITLE
I can't run the examples

### ISSUE THREAD

**Issue by whyygug** [HornedSungem/SungemSDK#2]
My device is a brand new **Raspberry Pi  3B** ，and I don't install any software other than the system pre-installed software，I installed SungemSDK as the instructions guided，but I can't run the examples you provide.  The error message is as follows:

> Traceback (most recent call last):
>  File "/home/pi/SungemSDK/examples/python/Hello2018.py", line 5, in <module>
>    import cv2, sys, numpy as np
>  File "/usr/local/lib/python3.5/dist-packages/cv2/__init__.py", line 4, in <module>
>    from .cv2 import *
> ImportError: libhdf5_serial.so.100: cannot open shared object file: No such file or directory

Every example show the same error message. Can you tell me how to solve this problem?  Does SungemSDK contain OpenCV? Do I have to install OpenCV before I install SungemSDK?

**Comment by HornedSungem** [comment]
Hi, thanks for buying our product. Yes, you will need to install OpenCV to run the examples. However this should be done through running the install.sh we provided. 

Could you please first try:

python3
```python
Import cv2
```

If this failed, you have to reinstall Python-OpenCV:

```
pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple python-opencv
```

**Comment by HornedSungem** [comment]
Please try to install some packages:
sudo apt-get install -y build-essential pkg-config
sudo apt-get install -y libjpeg-dev libtiff5-dev libjasper-dev libpng12-dev
sudo apt-get install -y libavcodec-dev libavformat-dev libswscale-dev libv4l-dev
sudo apt-get install -y libxvidcore-dev libx264-dev
sudo apt-get install -y libgtk2.0-dev libgtk-3-dev
sudo apt-get install -y libatlas-base-dev gfortran
sudo apt-get install -y libhdf5-dev libqtgui4 libqt4-test

**Comment by daixiangzi** [comment]
https://pypi.tuna.tsinghua.edu.cn/simple 你提供的这个源里面根本就没有 python-opecv

**Comment by HornedSungem** [comment]
请参考 #10 #5
