### ISSUE TITLE
Unable to run some of the DEMO on Raspberry Pi Zero W

### ISSUE THREAD

**Issue by jimaobian** [HornedSungem/SungemSDK#9]
The demo could run:
* Hello2018.py
* GetImage.py

The demo could not run:
* FaceDetector.py
* ImageRecognition.py
* ObjectDetector.py
* SceneRecorder.py
* SketchGuess.py

**Comment by HornedSungem** [comment]
Sorry. You need to re-plug the Horned Sungem when you try to run the second demo. This is a bug we are trying to fix.
